### ISSUE TITLE
It doesn't work((

### ISSUE THREAD

**Issue by ruslan200065** [CreeBoom2020/Bmw-F3x-6wa-cluster-with-simhub-for-beamng#1]
Hello dear friend. I tried to use your creation, but it wasn't successful. Before that, I tried a similar project and it was launched successfully. Here I encountered the problem that the dashboard does not respond in any way/does not turn on(

**Comment by CreeBoom2020** [comment]
Hey so did u Check that ur can Bus shield is geting initialized? If u Open the serial Monitor and Set the baudrate to i belive IT was 19200 you shoudl see If IT IS succesful or Not. And If nit then Check ur cs Pin. (Default is 10) And when u unplug the can Bus do u get a hood Open Error Message in the Cluster?

**Comment by cobi994** [comment]
i dont understand it can you help me

**Comment by CreeBoom2020** [comment]
Hi,
Whats Ur Problem?

**Comment by cobi994** [comment]
so i put the bmw_f_dc in the Arduino code and nothing happens

**Comment by CreeBoom2020** [comment]
What do u mean by putting the .ino in the arduino Code? U have to Copy IT in the document\arduino\libarys folder If u are in Windows

**Comment by cobi994** [comment]
so i tried the skech and it didnt work

**Comment by CreeBoom2020** [comment]
What didn't Work? The Cluster didn't Turn on? Or did the Code nit compile?

**Comment by cobi994** [comment]
yeah

**Comment by cobi994** [comment]
both

**Comment by CreeBoom2020** [comment]
Did u Install all of the libarys?

**Comment by cobi994** [comment]
wdym? what libarys?

**Comment by CreeBoom2020** [comment]
u need all of the libarys like mcp_can and so on.

**Comment by CreeBoom2020** [comment]
let me check what u needed again one moment

**Comment by cobi994** [comment]
ok

**Comment by cobi994** [comment]
what was it i needed?

**Comment by CreeBoom2020** [comment]
so in the resposetory there is now a file needed libarys. google all of them, download them, and install them. then u shoudl be good to go

**Comment by cobi994** [comment]
ok ill see how i go thanks

**Comment by CreeBoom2020** [comment]
and u coudl have messaged me on dc thats also no problem!

**Comment by cobi994** [comment]
oh sorry but im still having a problem with #include "Adafruit_GFX.h"

**Comment by CreeBoom2020** [comment]
did u download this? https://github.com/adafruit/Adafruit-GFX-Library

**Comment by cobi994** [comment]
![image](https://github.com/user-attachments/assets/299f47ce-d20d-4b87-9ded-aedf2b1ed9fa)
witch one

**Comment by CreeBoom2020** [comment]
just download the zip and install it via libary maneger

**Comment by CreeBoom2020** [comment]
![grafik](https://github.com/user-attachments/assets/3da9bebf-eadd-49f8-a35d-2410f3d0bf8f)

**Comment by cobi994** [comment]
where di i find the zip

**Comment by CreeBoom2020** [comment]
click on code and then download zip

**Comment by cobi994** [comment]
so any of  "Adafruit_GFX.h" them?

**Comment by CreeBoom2020** [comment]
yea just download the zip and install it in arduino ide.

**Comment by cobi994** [comment]
this is the problem 
![image](https://github.com/user-attachments/assets/4384faab-3522-4659-b689-93af3952474d)

**Comment by CreeBoom2020** [comment]
oki try to open the zip and copy the folder in to ur libary folder so documents\Arduino\libarys

**Comment by cobi994** [comment]
is there any other way that didnt work

**Comment by CreeBoom2020** [comment]
thats relay wierd, on my end it works like that. can u send a pic of ur Libary folder?

**Comment by cobi994** [comment]
the reason it didnt work is bc it dosent exsict
![image](https://github.com/user-attachments/assets/8d7dfa04-5325-46bc-a85b-6b83078e7afe)

**Comment by CreeBoom2020** [comment]
u can also try the libary maneger just type in Adafruit_GFX.
![grafik](https://github.com/user-attachments/assets/07e2c1d2-77da-45a8-9bb3-d4760f49aeb3)

**Comment by cobi994** [comment]
ok that is done what is this one FlowSerialRead.h

**Comment by CreeBoom2020** [comment]
that is in my folder with the ino and other files, u also have to copy that to the libarys folder

**Comment by cobi994** [comment]
what is it in the library manager on ide?

**Comment by CreeBoom2020** [comment]
the folder that u dowloaded here with the project.

**Comment by CreeBoom2020** [comment]
u need to copy that in to the libarys folder

**Comment by cobi994** [comment]
![image](https://github.com/user-attachments/assets/a7c2b117-0f21-434c-893d-51fdcbfc168e)
nothing came up when searched it

**Comment by CreeBoom2020** [comment]
C:\Users\***\Documents\Arduino\libraries to there BMW_F_DC.

**Comment by cobi994** [comment]
![image](https://github.com/user-attachments/assets/ad076967-6668-4197-8ff3-8aee034fb35f)
it dosent do anything i think

**Comment by CreeBoom2020** [comment]
copy that folder to ur libarys folder

**Comment by cobi994** [comment]
like everything there

**Comment by CreeBoom2020** [comment]
move the entire folder to libarys

**Comment by cobi994** [comment]
![image](https://github.com/user-attachments/assets/340c4e09-c822-43d4-a333-6e5a7a53a77b)
![image](https://github.com/user-attachments/assets/c842b04a-7679-4049-b41c-8bee4559aa58)
all of them?

**Comment by CreeBoom2020** [comment]
Yes

**Comment by CreeBoom2020** [comment]
https://github.com/user-attachments/assets/a01b9981-ca6b-4ede-862f-fd55cf8d6e44

**Comment by cobi994** [comment]
![image](https://github.com/user-attachments/assets/750f2d9c-1a73-4a87-b25a-53eebc651750)
this is the new problem

**Comment by CreeBoom2020** [comment]
did u install the mcp_can libary?

**Comment by cobi994** [comment]
i think

**Comment by CreeBoom2020** [comment]
just go throu the needed libarys file and download the zips and copy the folder inside them to the libarys folder or look if they are in the arduino libary store. Mcp_can is in the arduino store just go throu all of them.. :|

**Comment by cobi994** [comment]
![image](https://github.com/user-attachments/assets/8aa9e8fc-de95-4e7d-aee5-7a2b367458f1)
yep what do i do now?

**Comment by CreeBoom2020** [comment]
copy the entire folde in to the libarys folder

**Comment by cobi994** [comment]
![image](https://github.com/user-attachments/assets/b8594cdc-2642-4538-afbd-c4adc4fde30d)
this is now the problem

**Comment by CreeBoom2020** [comment]
is Simhub open? that error is with uploading to the arduino

**Comment by CreeBoom2020** [comment]
if Simhub isnt open unplug and plug ur arduino back in. and try to open arduino ide with admin premisions.

**Comment by cobi994** [comment]
its still not working i keep saying access denied

**Comment by CreeBoom2020** [comment]
is any programm open wich might use the arduino?

**Comment by cobi994** [comment]
i dont think so

**Comment by CreeBoom2020** [comment]
try a diferend usb port and try a diferent cable. and if ur serial monitor is open close it.

**Comment by cobi994** [comment]
![image](https://github.com/user-attachments/assets/8f90b685-ead1-481b-b393-85e3c2c68b72)

**Comment by CreeBoom2020** [comment]
u have to select ur arduino and serial port in the top 
![grafik](https://github.com/user-attachments/assets/281685ea-fe6d-4dc9-875e-94015751fe37)
and selec ur arduino in dc i saw a uno so uno.

**Comment by cobi994** [comment]
![image](https://github.com/user-attachments/assets/d1069e48-6596-498e-a163-1d31b100f008)

**Comment by CreeBoom2020** [comment]
try to restart ur pc may help:/

**Comment by cobi994** [comment]
ok

**Comment by cobi994** [comment]
![image](https://github.com/user-attachments/assets/1dbde726-a5bb-4b7d-aaa5-11b45f888b0e)
it still not work

**Comment by CreeBoom2020** [comment]
close simhub. dont open it! its accesing the arduino so no upload until its closed. open it after the upload

**Comment by cobi994** [comment]
ok it uploded but the cluster did nothing

**Comment by cobi994** [comment]
so what else do i have to do?

**Comment by CreeBoom2020** [comment]
are u using an original seeed studio canbus shield? if yes in arduino ide scrol on the top with all of the files till u see SHCustomprotocol.h or open it in a text editor in the BMW_f_DC folder wich is in ur libary folder and then look for "const int spiCS = 10;" and change the 10 to a 9 and reupload

**Comment by cobi994** [comment]
what am i reuploading?

**Comment by CreeBoom2020** [comment]
the scetch

**Comment by cobi994** [comment]
![image](https://github.com/user-attachments/assets/c0ab660c-38e0-4ec9-baaf-29e1d1ae20b8)
this worked ant the cluste is still off

**Comment by CreeBoom2020** [comment]
if u disconnect the canbus line from the shield do u get a hood open message?

**Comment by cobi994** [comment]
its on now

**Comment by CreeBoom2020** [comment]
the cluster?

**Comment by CreeBoom2020** [comment]
do u get a hood open message?

**Comment by cobi994** [comment]
yes

**Comment by CreeBoom2020** [comment]
show me a pic of the SHCustomProtocol.h file

**Comment by cobi994** [comment]
![image](https://github.com/user-attachments/assets/aede3309-4748-472c-9764-265b7f5a9be9)
what is your discord so i can show you what it is doing

**Comment by CreeBoom2020** [comment]
CreeBoom2020 are u cobi55

**Comment by cobi994** [comment]
yes that is me

**Comment by cobi994** [comment]
Sorry, what one was for the revs?
